---

- hosts: mlworker
  user: ubuntu
  sudo: True

  tasks:
    - apt: update_cache=yes
    - name: install common packages needed for python application development
      action: apt pkg={{item}} state=installed
      with_items:
        - git-core
        - unzip
        - libjpeg62
        - libjpeg62-dev
        - libfreetype6
        - libfreetype6-dev
        - zlib1g-dev
        - build-essential
        - python-dev
        - python-setuptools
        - python-imaging
        - python-matplotlib
        - python-setuptools
        - python-numpy
        - python-scipy
        - python-sklearn
        - libatlas-dev
        - libatlas3gf-base

    - name: install pip
      action: easy_install name=pip

    - name: symlink imaging library files
      action: file src=/usr/lib/x86_64-linux-gnu/libfreetype.so dest=/usr/lib/libfreetype.so state=link

    - name: symlink imaging library files
      action: file src=/usr/lib/x86_64-linux-gnu/libz.so dest=/usr/lib/libz.so state=link

    - name: symlink imaging library files
      action: file src=/usr/lib/x86_64-linux-gnu/libjpeg.so.62 dest=/usr/lib/x86_64-linux-gnu/libjpeg.so state=link

    - name: symlink imaging library files
      action: file src=/usr/lib/x86_64-linux-gnu/libjpeg.so dest=/usr/lib/libjpeg.so state=link
